"use client"

import { useMemo, useState } from "react"
import { ArrowUpRight, BarChart3, ChevronRight, CircleHelp, Menu, X } from "lucide-react"
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import "./styles.css"

type Match = { match_id:string; home_team:{name:string; crest_url:string}; away_team:{name:string; crest_url:string}; kickoff_at:string; home_win_probability:number; draw_probability:number; away_win_probability:number; predicted_home_goals:number; predicted_away_goals:number; most_likely_home_goals:number; most_likely_away_goals:number; scoreline_probabilities:Record<string,number>; explanation_summary:string|null }

const crest=(initials:string, color:string)=>`data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 80 80"><path fill="${color}" d="M8 8h64v40c0 17-14 26-32 30C22 74 8 65 8 48V8Z"/><text x="40" y="48" text-anchor="middle" fill="white" font-family="Arial" font-size="20" font-weight="700">${initials}</text></svg>`)}`
const matches:Match[]=[
 {match_id:"ars-lei",home_team:{name:"Arsenal",crest_url:crest("ARS","#d71920")},away_team:{name:"Leicester City",crest_url:crest("LEI","#2464ad")},kickoff_at:"2026-08-29T15:00:00Z",home_win_probability:.71,draw_probability:.17,away_win_probability:.12,predicted_home_goals:2.1,predicted_away_goals:.8,most_likely_home_goals:2,most_likely_away_goals:0,scoreline_probabilities:{"2-0":.142,"2-1":.111,"1-0":.104,"1-1":.092,"3-0":.083,"3-1":.068},explanation_summary:"Arsenal's home attack has generated the highest expected chance volume in the league across the last six matchdays. Leicester's transition threat keeps a clean sheet unlikely, but the model sees a controlled home win."},
 {match_id:"liv-bou",home_team:{name:"Liverpool",crest_url:crest("LIV","#c8102e")},away_team:{name:"Bournemouth",crest_url:crest("BOU","#b22d2d")},kickoff_at:"2026-08-29T12:30:00Z",home_win_probability:.76,draw_probability:.14,away_win_probability:.10,predicted_home_goals:2.4,predicted_away_goals:.7,most_likely_home_goals:2,most_likely_away_goals:0,scoreline_probabilities:{"2-0":.15,"3-0":.13,"2-1":.12,"1-0":.1},explanation_summary:"Liverpool's press and set-piece numbers create a wide gap in chance quality."},
 {match_id:"che-new",home_team:{name:"Chelsea",crest_url:crest("CHE","#034694")},away_team:{name:"Newcastle United",crest_url:crest("NEW","#444444")},kickoff_at:"2026-08-30T14:00:00Z",home_win_probability:.46,draw_probability:.26,away_win_probability:.28,predicted_home_goals:1.5,predicted_away_goals:1.2,most_likely_home_goals:1,most_likely_away_goals:1,scoreline_probabilities:{"1-1":.14,"2-1":.11,"1-0":.1,"0-1":.09},explanation_summary:"A tight midfield battle: Chelsea own territory while Newcastle carry the more dangerous counter."},
 {match_id:"mci-bha",home_team:{name:"Manchester City",crest_url:crest("MCI","#6cabdd")},away_team:{name:"Brighton",crest_url:crest("BHA","#0057b8")},kickoff_at:"2026-08-30T16:30:00Z",home_win_probability:.68,draw_probability:.18,away_win_probability:.14,predicted_home_goals:2.0,predicted_away_goals:1.0,most_likely_home_goals:2,most_likely_away_goals:1,scoreline_probabilities:{"2-1":.13,"2-0":.12,"1-0":.1,"3-1":.09},explanation_summary:"City's possession profile is a strong home signal, though Brighton's build-up can create one high-quality reply."},
 {match_id:"tot-avl",home_team:{name:"Tottenham",crest_url:crest("TOT","#132257")},away_team:{name:"Aston Villa",crest_url:crest("AVL","#670e36")},kickoff_at:"2026-08-30T13:00:00Z",home_win_probability:.41,draw_probability:.25,away_win_probability:.34,predicted_home_goals:1.6,predicted_away_goals:1.5,most_likely_home_goals:1,most_likely_away_goals:1,scoreline_probabilities:{"1-1":.13,"2-1":.11,"1-2":.1,"2-2":.08},explanation_summary:"The highest-variance fixture this weekend. Both sides push fullbacks high and concede space behind."},
 {match_id:"mun-ful",home_team:{name:"Manchester United",crest_url:crest("MUN","#da291c")},away_team:{name:"Fulham",crest_url:crest("FUL","#222222")},kickoff_at:"2026-08-31T19:00:00Z",home_win_probability:.55,draw_probability:.23,away_win_probability:.22,predicted_home_goals:1.7,predicted_away_goals:1.1,most_likely_home_goals:2,most_likely_away_goals:1,scoreline_probabilities:{"2-1":.13,"1-1":.12,"1-0":.1,"2-0":.09},explanation_summary:"A modest home edge, primarily driven by Old Trafford shot volume and Fulham's away defensive profile."}
]
const accuracy=[{week:"W1",model:38,bookmaker:41},{week:"W2",model:42,bookmaker:44},{week:"W3",model:40,bookmaker:43},{week:"W4",model:46,bookmaker:45},{week:"W5",model:44,bookmaker:46},{week:"W6",model:48,bookmaker:47},{week:"W7",model:47,bookmaker:48},{week:"W8",model:50,bookmaker:48}]
const pct=(n:number)=>`${Math.round(n*100)}%`
const time=(iso:string)=>new Date(iso).toLocaleDateString("en-GB",{weekday:"short",day:"numeric",month:"short"})
const renderMatch=(m:Match,i:number,onSelect:(m:Match)=>void)=><button className="match" key={m.match_id} onClick={()=>onSelect(m)}><span className="match-number">0{i+2}</span><span className="teams"><span>{m.home_team.name}</span><b>{"-"}</b><span>{m.away_team.name}</span></span><span className="favorite">{pct(Math.max(m.home_win_probability,m.away_win_probability))}</span><ArrowUpRight className="arrow"/></button>

export default function Page(){const [tab,setTab]=useState("Overview"); const [selected,setSelected]=useState<Match|null>(null); const [mobile,setMobile]=useState(false); const featured=matches[0];
 const nav=(x:string)=>{setTab(x); setMobile(false); document.getElementById(x.toLowerCase())?.scrollIntoView({behavior:"smooth"})}
 return <main><header><div className="brand"><span className="brand-mark">P</span><span>FORM<span className="accent">/</span>90</span></div><nav className={mobile?"open":""}>{["Overview","Fixtures","Performance"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>nav(x)}>{x}</button>)}</nav><button className="menu" aria-label="Toggle menu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><button className="season">2026/27 <ChevronRight/></button></header>
 <section className="hero" id="overview"><div className="eyebrow"><span className="live-dot"/> GAMEWEEK 03 <span className="slash">/</span> 28 AUG 2026</div><h1>Every match.<br/><em>Read differently.</em></h1><p className="lede">A transparent statistical view of the Premier League — powered by a Poisson/Dixon-Coles model.</p><button className="text-link" onClick={()=>nav("Fixtures")}>Explore this gameweek <ArrowUpRight/></button></section>
 <section className="featured"><div className="section-label">FEATURED FIXTURE <span>01 / 06</span></div><div className="feature-grid"><div className="fixture-title"><div className="fixture-meta">SAT 29 AUG <span>15:00</span> <span className="pill">EMIRATES STADIUM</span></div><h2>{featured.home_team.name}<br/><span>vs</span> {featured.away_team.name}</h2><p>{featured.explanation_summary}</p><button className="outline" onClick={()=>setSelected(featured)}>View full prediction <ArrowUpRight/></button></div><div className="probability"><div className="crest-row"><img src={featured.home_team.crest_url} alt="Arsenal crest"/><div className="versus">VS</div><img src={featured.away_team.crest_url} alt="Leicester City crest"/></div><div className="big-prob"><strong>{pct(featured.home_win_probability)}</strong><span>home win</span></div><div className="bar"><i style={{width:`${featured.home_win_probability*100}%`}}/><i style={{width:`${featured.draw_probability*100}%`}}/><i style={{width:`${featured.away_win_probability*100}%`}}/></div><div className="bar-labels"><span>ARS {pct(featured.home_win_probability)}</span><span>DRAW {pct(featured.draw_probability)}</span><span>LEI {pct(featured.away_win_probability)}</span></div></div></div></section>
 <section className="fixtures" id="fixtures"><div className="section-heading"><div><div className="eyebrow">THE FULL SLATE</div><h2>This week&apos;s fixtures</h2></div><span className="count">{matches.length} MATCHES</span></div><div className="match-list">{matches.slice(1).map((m,i)=>renderMatch(m,i,setSelected))}</div></section>
 <section className="performance" id="performance"><div className="performance-copy"><div className="eyebrow">MODEL PERFORMANCE</div><h2>Gets sharper<br/><em>with every week.</em></h2><p>We backtest our predictions against actual results and bookmaker consensus. No black box — just a model that earns its edge.</p><button className="text-link">Read methodology <ArrowUpRight/></button></div><div className="chart-panel"><div className="chart-top"><span>ACCURACY OVER TIME</span><div><b><i className="dot model"/> Model</b><b><i className="dot book"/> Bookmaker</b></div></div><div className="chart"><ResponsiveContainer width="100%" height={230}><LineChart data={accuracy} margin={{top:10,right:10,left:-25,bottom:0}}><XAxis dataKey="week" stroke="var(--muted)" tickLine={false} axisLine={false}/><YAxis domain={[30,55]} stroke="var(--muted)" tickLine={false} axisLine={false} tickFormatter={v=>`${v}%`}/><Tooltip contentStyle={{background:"#171722",border:"1px solid #343342",borderRadius:8}} formatter={(v)=>`${v}%`}/><Line type="monotone" dataKey="model" stroke="var(--accent)" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="bookmaker" stroke="var(--muted)" strokeWidth={2} strokeDasharray="4 4" dot={false}/></LineChart></ResponsiveContainer></div><div className="metrics"><div><strong>43.5%</strong><span>Model accuracy</span></div><div><strong>1.06</strong><span>Log loss</span></div><div><strong>482</strong><span>Matches evaluated</span></div></div></div></section>
 <footer><div className="brand"><span className="brand-mark">P</span><span>FORM<span className="accent">/</span>90</span></div><span>Built for the curious fan.</span><span>Data refreshes every gameweek <CircleHelp/></span></footer>
 {selected&&<div className="overlay" onClick={()=>setSelected(null)}><article className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)} aria-label="Close"><X/></button><div className="eyebrow">MATCH PREDICTION <span>{time(selected.kickoff_at)}</span></div><h2>{selected.home_team.name} <em>vs</em> {selected.away_team.name}</h2><div className="modal-score"><div><img src={selected.home_team.crest_url} alt=""/><strong>{selected.most_likely_home_goals}</strong></div><span>—</span><div><strong>{selected.most_likely_away_goals}</strong><img src={selected.away_team.crest_url} alt=""/></div></div><div className="modal-stats"><div><span>WIN PROBABILITY</span><b>{pct(selected.home_win_probability)} <small>—</small> {pct(selected.draw_probability)} <small>—</small> {pct(selected.away_win_probability)}</b><p>Home <i/> Draw <i/> Away</p></div><div><span>EXPECTED GOALS</span><b>{selected.predicted_home_goals.toFixed(1)} <small>—</small> {selected.predicted_away_goals.toFixed(1)}</b></div></div><h3>Most likely scorelines</h3><div className="score-grid">{Object.entries(selected.scoreline_probabilities).map(([score,p])=><div key={score}><b>{score}</b><span>{pct(p)}</span></div>)}</div><p className="explanation">{selected.explanation_summary}</p></article></div>}</main>
}
